pipeline {
  agent any
  environment {
    PATH = "usr/bin:/bin:/opt/homebrew/bin"
  }
  stages {
    stage('pull'){
      steps{
        git branch: 'main',url:'https://github.com/PraveenKuber/Amazon-Jenkins.git'
      }
    }
    stage('compile'){
      steps{
        sh 'mvn clean install'
      }
    }
    stage('build'){
      steps{
        sh 'mvn clean install'
      }
    }
  }
  post {
    success{
      echo 'Build success'
    }
    failure {
      echo 'Failure in the build'
    }
  }
}

  
